USE DataSalud_Peru;
GO

CREATE FUNCTION dbo.fn_NormalizarTexto (@Texto NVARCHAR(255))
RETURNS VARCHAR(255)
AS
BEGIN
    RETURN CASE WHEN @Texto IS NULL THEN NULL ELSE UPPER(LTRIM(RTRIM(@Texto))) END;
END;
GO
